INSERT INTO TB_CATEGORY (name, created_At) VALUES ('BOOKS', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('ELECTRONICS', NOW());
INSERT INTO TB_CATEGORY (name, created_At) VALUES ('COMPUTERS', NOW());
INSERT INTO TB_CATEGORY (name) VALUES ('MOUSE');